
# Experiment Configuration
experiment:
  verbose: False
  single_layer: True
  target_index: 0 # This will be iterated in main_config.py
  batch_size: 1
  experiment_num: "|PseudoLabelling|"
  num_epoch: 20
  eval_step: 1
  save_step: 2
  init_learning_rate: 0.0015
  classifier_weight: 1
  discriminator_weight: 1
  extractor_weight: 1
  entropy_weight: 1
  grl_weight: 1.25
  label_smooth: 0.1
  weight_decay: 5e-4
  amsgrad: True
  t_max: 10
  num_clusters: 4
  num_classes: 2
  clustering_step: 2
  data_path: "./skripsi_code/data/parquet/"
  input_nodes: 39
  use_cluster: True

domain_list:
  - "NF-UNSW-NB15-v2"
  - "NF-CSE-CIC-IDS2018-v2"
  - "NF-ToN-IoT-v2"

domain_reweighting:
  - 23
  - 187
  - 169

label_reweighting:
  - [0.8735, 0.1265]
  - [0.8307, 0.1693]
  - [0.0356, 0.9644]

hidden_nodes: [64, 32, 16, 10]
class_nodes: [64, 32, 16]
